# Generated by Django 4.2.4 on 2023-08-20 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.JSONField(null=True)),
                ("price_multiplier", models.FloatField()),
                ("base_price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("x_coord", models.BigIntegerField()),
                ("y_coord", models.BigIntegerField()),
                ("z_coord", models.BigIntegerField()),
                ("planet_tax_rate", models.FloatField()),
                ("description", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("price_multiplier", models.FloatField()),
                ("base_price", models.FloatField()),
                ("description", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_count", models.IntegerField()),
                ("journey_date", models.DateField()),
                ("booking_price", models.FloatField()),
                ("details", models.JSONField(null=True)),
                (
                    "end_planet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_planet",
                        to="cms.planet",
                    ),
                ),
                (
                    "ship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cms.shiptype"
                    ),
                ),
                (
                    "start_planet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_planet",
                        to="cms.planet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
