# Generated by Django 4.2.4 on 2023-08-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_package_planet_shiptype_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="package",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="cms.package"
            ),
            preserve_default=False,
        ),
    ]
