# Generated by Django 4.2.4 on 2023-08-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_booking_package"),
    ]

    operations = [
        migrations.CreateModel(
            name="TumorDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("detection_class", models.CharField(max_length=256)),
                ("trained", models.BooleanField(default=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("edited_datetime", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
