# Generated by Django 4.2.4 on 2023-08-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_tumordetection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tumordetection',
            name='path',
        ),
        migrations.AddField(
            model_name='tumordetection',
            name='file',
            field=models.FileField(default='a', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
